### ISSUE TITLE
Pixel Aspect Ratio not respected when using Media Foundation

### ISSUE THREAD

**Issue by v2k** [RenderHeads/UnityPlugin-AVProVideo#1237]
Videos appear squished with wrong aspect ratio

**Setup**
 - Unity version: 2019.4.40f1
 - 2.5.0f1-ultra
 - Operating system version: Win 10/11

**To Reproduce**
1. Try to play video in Media Player component
2. Notice aspect ratio is wrong. (width is wrong)

**Screenshots**
![image](https://user-images.githubusercontent.com/608250/180284631-c30ec676-75c2-4c48-b318-10182f4a10f4.png)

Squished:
![image](https://user-images.githubusercontent.com/608250/180285186-23b07907-1152-453c-a5b3-38570aa4842f.png)

**Videos**
emailed

**Comment by Chris-RH** [comment]
Email received, we'll check it out, thank you.

**Comment by AndrewRH** [comment]
We have fixed this and the fix will be in the next release.

We're still using the unscaled texture (960x720) but during display using the DisplayUGUI, DisplayIMGUI or ResolveToTexture methods we are rendering the content stretched to the correct DAR (display aspect ratio)

Thanks,

**Comment by v2k** [comment]
Awesome!  We will verify in the next release

**Comment by Chris-RH** [comment]
The latest update has just been released. Please let us know if the problem is fixed :)

**Comment by drinsley** [comment]
Thanks for the update, it's fixed for direct show.

But it's not fixed for media foundation, using hap on, when using a hap clip
![image](https://user-images.githubusercontent.com/8988151/181834685-5f054664-b677-4f35-bb62-45c0adb800a1.png)

**Comment by Chris-RH** [comment]
Could you send us a copy of this file you are using please?

**Comment by v2k** [comment]
You can generally take any clip and just fun ffmpeg:

`ffmpeg -i video.mpg -c:v hap video_hap.mov`

**Comment by drinsley** [comment]
emailed with a link to the original and hap versions

**Comment by Chris-RH** [comment]
Thanks, we've received them, much appreciated :) Its always handy to work with exactly the file that you are having problems with :)

**Comment by RichRH** [comment]
A fix has been comitted for the Media Foundation path and will be in the next release.

Cheers,

**Comment by Chris-RH** [comment]
This has hopefully been fixed now with the release of version 2.6.0.

**Comment by drinsley** [comment]
Thanks it is fixed with the new update
