### ISSUE TITLE
Crashes on iOS  UnityGfxDeviceWorker

### ISSUE THREAD

**Issue by yangwz** [RenderHeads/UnityPlugin-AVProVideo#1570]
Describe the issue
Our game crashes after scene switch, and there are videos playing in these scenes
The issue occurs randomly. Device Model:iphone 6plus - iphone14 pro max

 - Unity version: 2020.3.38
 - AVPro Video version 2.8.0(number and edition (trial/core/ultra/enterprise)): 
 - Operating system version: os version：iOS12.4.6 。 xcode version：14.2
 - Device model: iphone 6plus。 
 - Video specs (resolution, frame-rate, codec, file size): 

To Reproduce
launch app and keep tap the button "videoscene2","videoscene1","novideoscene" to switch scenes.
The app will crash in a few minutes

Logs
[log.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/11830082/log.txt)

Screenshots
![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/11922271/a4f778b8-febb-4a38-b53a-23d95c1d7a14)

we also have a demo send to unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
What is the full error message for UnityGfxDeviceWorker (30): EXC_BAD_ACCESS...?

The iphone 6plus is from 2014. Do you have a newer device to test on?

**Comment by yangwz** [comment]
> What is the full error message for UnityGfxDeviceWorker (30): EXC_BAD_ACCESS...?
> 
> The iphone 6plus is from 2014. Do you have a newer device to test on?

full error message is UnityGfxDeviceWorker (29): EXC_BAD_ACCESS (code=1, address=0x116cc228)

this screenshot is collect by our crashreport log by crashsight
![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/11922271/bb205033-485c-4f5a-97ed-12033facacba)
![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/11922271/45ac0615-fe1a-40c1-9745-1160d689a2e5)


use iphone 6plus the app，high probability crash after change scene 20 times
i will try to reproduce this issues with iphone 14 pro max

**Comment by yangwz** [comment]
@Chris-RH
 If I comment out 292 lines of code AppleMediaPlayer.cs  or turn off multithreaded rendering, it won't crash。
Do you have any ideas
![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/11922271/b531582a-f79b-432c-956f-f269e18a1b94)

**Comment by Chris-RH** [comment]
did you manage to reproduce it on the iphone 14 max?
if so, did it occur as frequently?
what version of iOS is it?

**Comment by yangwz** [comment]
I can't reproduce in the demo on the ip14 promax 
but our game in appstore, Crashing range in iOS versions 12.0-16.5
![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/11922271/31aa1602-13ce-4ad6-91d4-367cecf7985d)
![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/11922271/e2378497-8b1f-495e-9f13-6c9a6185812d)

**Comment by yangwz** [comment]
@Chris-RH 
hi, i did reprodice the issue on the iphone14 promax
it is log
[crashlog.log](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/11848731/crashlog.log)

**Comment by Chris-RH** [comment]
The line with the objc_retain function indicates that Objective-C runtime can’t message objects deallocated from memory, causing a crash. 
It is probably timing related, so it is more likely to occur in older (slower) devices. Saying that, it will look skewed towards more recent iOS versions as more users will be using those versions.

**Comment by yangwz** [comment]
So how can we solve this problem？Is this issue related to this plugin？

**Comment by yangwz** [comment]
@Chris-RH 
I have no idea why try to calling update when CloseMedia。 could this be the cause of the issue
The function CloseMedia at AppleMediaPlayer.cs
![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/11922271/9a496571-5fed-4ea5-8205-79de0fe0bf29)

**Comment by Chris-RH** [comment]
We are struggling to reproduce this crash in-house.

**Comment by MorrisRH** [comment]
I've reproduced the issue and am currently looking for a solution.

**Comment by MorrisRH** [comment]
This issue has been fixed and the fix will make it into the next release.

**Comment by MorrisRH** [comment]
Linking #1481 as it's the same issue

**Comment by supernickgo** [comment]
This is a very terrible crash and shows that your thread organization is very problematic.

**Comment by supernickgo** [comment]
This crash, I don't think has anything to do with multithreaded rendering. It looks like the video decoding thread updated the texture, didn't stop in time.  Video decoding and updating should be stopped before the texture is destroyed。

**Comment by Chris-RH** [comment]
Hi @supernickgo, 

Are you saying that you are still finding this crash in AVPro Video version 2.8.1?

**Comment by supernickgo** [comment]
> Hi @supernickgo,
> 
> Are you saying that you are still finding this crash in AVPro Video version 2.8.1?

No,  we have yet to upgrade. I just can't understande , it should be an obvious bug。 or we need a callback to destory texture.  this bug took me a long time to find out .

**Comment by yangwz** [comment]
hi @MorrisRH 
It seems to have been fixed。but we have new issue
this is crash log
[ioscrash.log](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/11935329/ioscrash.log)
It seems like that the video thread scheduled is too frequent

**Comment by MorrisRH** [comment]
Hey @yangwz,
Could you provide details about the media you're playing, and any specific overrides you have applied to the media player instance and anything you've changed from defaults in Unity's iOS player settings.
Are you running multiple media player instances? If so how many simultaneously?

**Comment by yangwz** [comment]
> Hey @yangwz, Could you provide details about the media you're playing, and any specific overrides you have applied to the media player instance and anything you've changed from defaults in Unity's iOS player settings. Are you running multiple media player instances? If so how many simultaneously?

player settings
![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/11922271/1a5dffc1-3bf6-424a-b54f-e21f90d2df68)
media instance setting
![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/11922271/f49f1d38-d5e8-490c-a0d2-8440f0b0d2ad)

We have two media instances in each scene
this issue  occurs when we frequently switch scenes

**Comment by helinkayabass** [comment]
Hello,

We're still experiencing the same issue occasionally that causes our application to crash. This is occurring within an environment using AVPro version 2.9.1 and Unity 2021.3.21f1. The crash happens under specific conditions, particularly when a GameObject with a child object containing a MediaPlayer component (actively playing a video) is destroyed.

Crash Details
The crash isn't consistent but has been noted several times. Here's the detailed crash log for your reference:

Error: Crashed: UnityGfxDeviceWorker
Stack Trace:
libobjc.A.dylib at objc_retain (address: 0x39d0)
UnityFramework at TexturesMetal::AddCreatedTexture (file: TexturesMetal.mm, line: 502)
UnityFramework at GfxDeviceWorker::RunCommand (file: GfxDeviceWorker.cpp, line: 1156)
UnityFramework at GfxDeviceWorkerAutoreleasePoolProxy (file: GfxDeviceMetal.mm, line: 5749)
UnityFramework at GfxDeviceWorker::RunExt (file: GfxDeviceWorker.cpp, line: 394)
UnityFramework at GfxDeviceWorker::RunGfxDeviceWorker (file: GfxDeviceWorker.cpp, line: 358)
UnityFramework at Thread::RunThreadWrapper (file: Thread.cpp, line: 82)
libsystem_pthread.dylib with _pthread_start and thread_start

**Comment by qiji1389** [comment]
> Hello,
> 
> We're still experiencing the same issue occasionally that causes our application to crash. This is occurring within an environment using AVPro version 2.9.1 and Unity 2021.3.21f1. The crash happens under specific conditions, particularly when a GameObject with a child object containing a MediaPlayer component (actively playing a video) is destroyed.
> 
> Crash Details The crash isn't consistent but has been noted several times. Here's the detailed crash log for your reference:
> 
> Error: Crashed: UnityGfxDeviceWorker Stack Trace: libobjc.A.dylib at objc_retain (address: 0x39d0) UnityFramework at TexturesMetal::AddCreatedTexture (file: TexturesMetal.mm, line: 502) UnityFramework at GfxDeviceWorker::RunCommand (file: GfxDeviceWorker.cpp, line: 1156) UnityFramework at GfxDeviceWorkerAutoreleasePoolProxy (file: GfxDeviceMetal.mm, line: 5749) UnityFramework at GfxDeviceWorker::RunExt (file: GfxDeviceWorker.cpp, line: 394) UnityFramework at GfxDeviceWorker::RunGfxDeviceWorker (file: GfxDeviceWorker.cpp, line: 358) UnityFramework at Thread::RunThreadWrapper (file: Thread.cpp, line: 82) libsystem_pthread.dylib with _pthread_start and thread_start

Has this issue been resolved on AVPro 2.9.x? We are getting exactly same crash on iOS platform. Our app just crashes randomly with same crash log when we looping between different videos. We are using AVPro 2.9.0 and Unity 2019. 4.38.
