### ISSUE TITLE
[AvProVideo] version does not match issue before playing video.

### ISSUE THREAD

**Issue by pnkjstha** [RenderHeads/UnityPlugin-AVProVideo#1608]
**Describe the issue**
While playing video with latest AvProVideo ultra edition version in iOS app downloaded from TestFlight shows the version does not match message in AvProVideo player view.

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.3f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)):  Version 2.8.4  (Ultra Edition)
 - Operating system version: macOS 13.2.1 (22D68)
 - Device model: iPhone X

**Screenshots**
![IMG_9332](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/105374590/0c2ab4a1-ff11-4a53-80db-2bf3ac6b324a)

**Videos**
If applicable, add a copy of your video or the URL

https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/105374590/99cf3c49-1770-41c5-9763-e7a6206053bd

**Comment by Chris-RH** [comment]
Strange, we fixed this a couple of months ago with 2.8.1.  
What version of xcode are you using?

**Comment by pnkjstha** [comment]
Xcode Version 14.2 (14C18)

**Comment by MorrisRH** [comment]
Linking #973

**Comment by pnkjstha** [comment]
I have updated to latest AvProVideo version but the issue is still shown after installing from TestFlight app.
Error message is also showing while running from simulator in unity editor.
Updated AvProVideo version is 2.8.4.

**Comment by pnkjstha** [comment]
[AVProVideo] Plugin version number 2.7.1-trial build 1606 doesn't match the expected version number 2.7.3.  It looks like the plugin didn't upgrade correctly.  To resolve this please restart Unity and try to upgrade the package again.

This is shown in console. But AvproVideo package is already updated to version 2.8.4.

**Comment by Chris-RH** [comment]
Could you retry it in a new project with just AVPro Video please?
Could you supply the xcode log please

**Comment by Chris-RH** [comment]
Closed due to lack of reply
