### ISSUE TITLE
Playlist Media Player Does Not Play Video When Using the Same Link That Was Played Once

### ISSUE THREAD

**Issue by Fasilkallot** [RenderHeads/UnityPlugin-AVProVideo#1826]
When attempting to play a video using a URL that has already been played within the same playlist item, the video is not displayed on the screen. However, upon inspection of the playlist component, it indicates that the video is playing. This issue occurs specifically when the video is played within the same playlist item. When the video is played with another playlist item, it appears to function correctly..

 - Unity version: 2023.2.3f
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.9.3(Core Edition)
 - Operating system version: Android 14
 - Device model: Oneplus 8T

**To Reproduce**
1.  Add two playlist items to the playlist component.
2. Set each playlist item with a different video url.
3. Play the Scene
4. When the video transitions to the next playlist item, press the "prev" button in component or action to return to the previous video.

**Comment by Ste-RH** [comment]
Sorry for the slow response @Fasilkallot .  Does this happen in Editor, or on an Android device?

**Comment by Fasilkallot** [comment]
Hi @Ste-RH,

Thank you for getting back to me. This issue occurs when checking in the Unity Editor. On an Android device, I found that the video gets stuck on the first frame while the audio continues to play normally. However, if the video finishes, the next video plays normally. This issue happens with different video links and can occur on some devices. If we restart the video, the problem often doesn’t reappear.

**Comment by Ste-RH** [comment]
Have you tried reproducing in v3.0.11 @Fasilkallot ?

**Comment by Fasilkallot** [comment]
I haven’t tried reproducing the issue in v3.0.11 because I’m currently using the core edition of 2.9.3 and am not receiving any updates. When I attempt to update manually, it indicates that I would need to purchase the new version again @Ste-RH .

**Comment by Chris-RH** [comment]
Yes, AVPro Video version 2 has been depreciated and is no longer receiving any updates.  There is a [discounted upgrade path ](https://renderheads.com/content/docs/AVProVideo-v3/articles/download.html#owners-of-avpro-video-2x)from AVPro Video version 2 to AVPro Video version 3.

**Comment by Ste-RH** [comment]
As Chris says.  We are no longer supporting v2.x.  It was deprecated 3 months after we released v3.x in March 2024.

I would advise testing the issue against the free watermarked trial version of v3.x as, if there is a bug, this is the version we would look to offer a fix in.

**Comment by Fasilkallot** [comment]
Thank you for the information. I understand that AVPro Video version 2 has been deprecated and is no longer receiving updates. However, it’s concerning that even existing customers are being asked to pay for the upgrade to version 3. Given that we can only use the core edition for 6 months after purchase, it seems a bit unfair to have to pay again for an upgrade. Is there a way to address this for existing customers who have been using version 2 @Chris-RH  ?

**Comment by Chris-RH** [comment]
Hi @Fasilkallot, 

There is absolutely no obligation to upgrade to AVPro Video version 3.  You can continue to use AVPro Video version 2 (or indeed version 1, as some users do) for as long as you'd like.  There will just be no further updates or bug fixes.   If you require the updated features or bug fixes that are in AVPro Video 3, then you will need to upgrade.

We do state in our [documentation](https://renderheads.com/content/docs/AVProVideo/articles/download.html#future-updates) that our assets have a minimum of a [2 year life cycle](https://renderheads.com/content/docs/AVProVideo-v3/articles/download.html#future-updates).  In fact AVPro Video was over 3 years old when it was depreciated.

We offered a grace period, which meant that AVPro Video version 3 was free to anyone who had bought AVPro Video version 2 within 60 days of version 3's release.  Current AVPro Video version 2 license holders receive a healthy discount if they choose to upgrade to AVPro Video version 3.

**Comment by Fasilkallot** [comment]
Hi @Fasilkallot,

I understand that there is no obligation to upgrade to AVPro Video version 3, and I appreciate the clarification on the life cycle of the asset and the grace period for upgrades.

However, the issues mentioned earlier are still present in version 2, and since we are not actively working on projects with AVPro, we haven’t been as aware of these issues. Even with the discount, the cost to upgrade to version 3 is $225. Considering that we paid $450 for the core edition with only 6 months of usage, this additional cost for an upgrade seems quite high and feels unfair given the situation.

Is there any possibility of further assistance or a different solution for existing customers who are facing these concerns?

**Comment by Fasilkallot** [comment]
Hi @Chris-RH ,

I understand that there is no obligation to upgrade to AVPro Video version 3, and I appreciate the clarification on the life cycle of the asset and the grace period for upgrades.

However, the issues mentioned earlier are still present in version 2, and since we are not actively working on projects with AVPro, we haven’t been as aware of these issues. Even with the discount, the cost to upgrade to version 3 is $225. Considering that we paid $450 for the core edition with only 6 months of usage, this additional cost for an upgrade seems quite high and feels unfair given the situation.

Is there any possibility of further assistance or a different solution for existing customers who are facing these concerns?

**Comment by Ste-RH** [comment]
As outlined, deprecated versions of AVPro Video will not suddenly stop working.  Therefore you do not only have 6 months of usage, you have an indefinite time of usage.

Maybe you would prefer if we had a business model that did not offer support of any duration, no updates, no feature additions?  I am sure as fellow developers you will appreciate - all this takes planning, time, and therefore requires a viable business model.  We have considered a subscription based system, but Unity currently does not support this as part of their eco system.  Therefore, this is the model we have adopted.  If this does not fit with your business model/practices...then you are naturally free to choose purchase/use another asset, or even implement your own solution.

We have been/are very transparent with how and when we deliver new major versions (as a side note, most of the major new features we implement would be impossible if we did not overhaul the asset periodically) and developers are free to purchase/use the asset, or not.

As a side note, we have always traditionally tried to help developers with any issues they are having with deprecated versions.  We are under no obligation to do this, but we hate to leave somebody with no path to a solution.

Lastly, I am sure you can appreciate that multiple replies to a question we have answered already takes time...time we could better spend trying to get your team and others to solutions for the issue being faced.

**Comment by Ste-RH** [comment]
> Hi @Ste-RH,
> 
> Thank you for getting back to me. This issue occurs when checking in the Unity Editor. On an Android device, I found that the video gets stuck on the first frame while the audio continues to play normally. However, if the video finishes, the next video plays normally. This issue happens with different video links and can occur on some devices. If we restart the video, the problem often doesn’t reappear.

Does this happen when using two of the sample videos provided with the asset...loading our of StreamingAssets?  If not, does this happen with the same two sample videos off a server?  We cannot reproduce the issue you are reporting in either v2.x or v3.x on Windows(editor) or Android(device).

**Comment by Fasilkallot** [comment]
Hi @Ste-RH,

The issue arises when using the playlist media player to play videos and switch between them, particularly when the videos are viewed in 360 and streamed via HLS from the web. This problem does not consistently occur with the two sample videos provided with the asset, whether they are loaded from a server. Additionally, the issue happens intermittently and not on a regular basis.

**Comment by Ste-RH** [comment]
"not consistently occur"

1) So it still happens using the sample videos?

2) Are you just clicking next/prev on the PlaylistMediaPlayer component in the instpector?

![image](https://github.com/user-attachments/assets/cbd5f2de-2823-423f-b652-14e7f759a018)

3) Does it happen in the Demo_Playlist scene (without modification)?

**Comment by Fasilkallot** [comment]
The issue seems to occur when streaming from a server using a URL. You can test it by using the "prev" and "next" controls within the editor. Please let me know if you need any additional information.

**Comment by Chris-RH** [comment]
Just wanting to confirm.  Did you check that the issue is still occurring in the [trial version](https://github.com/RenderHeads/UnityPlugin-AVProVideo/releases) of AVPro Video version 3?

**Comment by Fasilkallot** [comment]
I’ve tested it a few times, and it seems to be working fine in that version.

**Comment by Fasilkallot** [comment]
Hi Chris,
![Screenshot_2024-09-18-11-40-40-78_6db678231275f23f4e2fa72c692645be](https://github.com/user-attachments/assets/4f47c046-677c-47e4-8583-221033ef478d)

Thank you for your prompt response and for the information regarding the upgrade path. I’ve purchased and updated to AVPro Video version 3.0.11, but I’m now encountering a new issue: there’s a black line overlay appearing on my 360 VR video when played on Android using Google VR. This issue wasn’t present when I was using AVPro version 2.

Interestingly, I tested the trial version of version 3, and the problem did not occur there. Could you please provide guidance on how to resolve this issue? Any assistance would be greatly appreciated.

Kind regards,

Muhammed Fasil K

**Comment by Fasilkallot** [comment]
Hi Chris,

Thank you for your prompt response and for the information regarding the upgrade path. I’ve purchased and updated to AVPro Video version 3.0.11, but I’m now encountering a new issue: there’s a black line overlay appearing on my 360 VR video when played on Android using Google VR. This issue wasn’t present when I was using AVPro version 2.

Interestingly, I tested the trial version of version 3, and the problem did not occur there. Could you please provide guidance on how to resolve this issue? Any assistance would be greatly appreciated.

Kind regards,

Muhammed Fasil K
![Screenshot_2024-09-18-11-40-40-78_6db678231275f23f4e2fa72c692645be](https://github.com/user-attachments/assets/2e57cbd4-2c64-47d7-809d-1ac3a7a75b66)

**Comment by Chris-RH** [comment]
Hi @Fasilkallot 
Please can you make a new issue for this
