### ISSUE TITLE
[Question] current state iOS memory leak issue

### ISSUE THREAD

**Issue by aryansaurav** [RenderHeads/UnityPlugin-AVProVideo#2247]
### AVPro Video Version

2.9.1

### Which platform is your question for?

iOS

### Your question

Hello Render Heads Team,

We have noticed that memory leak on iOS platform both iPad and iPhone OS version 18.4.
We believe it might be coming from AV Pro. 

Platform: iOS
Device: iPhone 12 and iPad 2022
Media type: HLS video streamed with https URL

Streaming works perfectly, there is no issue in playback but the app will obviously crash after few mins of usage. What's more puzzling is that the memory usage does not go down even on switching videos.
On iPad we see the memory usage steadily go up from initial 400 MB all the way to 1.8 GB, increasing gradually with time during media playback.

We noted some old GitHub issues on memory leak on iOS platform. Was it not already fixed in version 2.7? We are encountering it on v2.9.1 now!

We are still using v2.9.1 (to avoid hassles in upgrading) despite purchasing the upgrade for 3.x version. 
We will assign to our developer to upgrade if it can help in fixing this issue.
 
Could you please confirm if the memory leak on iOS has indeed been fixed in versions 3.x.x?

**Comment by Chris-RH** [comment]
I'm not aware of any memory leak.
I would suggest just opening a new project using AVPro vide version 3 and seeing if you are able to reproduce the leak.
Please note that as AVPro Video version 2 is depreciated, it is no longer receiving any fixes or updates.

**Comment by MorrisRH** [comment]
We were not aware of any memory issues when we released the final version 2 (2.9.3) of AVPro Video. However this was only tested against the iOS versions available at the time (iOS 16 IIRC) so it is entirely possible that more recent changes to iOS have lead to this behaviour. It's also possible that more recent Unity versions have introduced this behaviour as well.

To the best of our knowledge there are no issues with memory in the latest version 3 (3.2.6).

**Comment by aryansaurav** [comment]
Ok thank you Chris, Morris for your comments. I had seen the old GitHub
issues but those might have been on older versions of unity and ios.

I agree with your point that the new memory leak might be coming from the
updated unity version and ios version.

Perhaps, the best would be to just test with the latest version of avpro on
latest unity (6.x) and latest iOS version. Will get back if the issue
persists.
Thanks

**Comment by Chris-RH** [comment]
Can you open up a proper bug report for this and fill in all the details please.  We especially need info about what media you are playing (url is helpful) and what playback speeds (how fast and how slow) you are using.

**Comment by MorrisRH** [comment]
Testing here we're seeing no memory leaks on Android nor iOS when changing the playback rate.

**Comment by aryansaurav** [comment]
It seems that we were able to fix the memory leak issue after upgrading to
AVPro 3.2, some garbage collection calls and using recommended speed values
(we were using 0.33 earlier).
Though, our app still crashes occasionally, now it's not due to memory
leak. And it probably is no longer coming from AVPro!
If there are any other AV Pro related problems, we will create a new Github
issue as Chris suggested.

Thank you again for your support Render Heads Team!
