### ISSUE TITLE
Video at URL wont play on MAC or IOS but plays on PC and ANDROID

### ISSUE THREAD

**Issue by nsmith1024** [RenderHeads/UnityPlugin-AVProVideo#424]
**Describe the bug**

I present this URL to the player on MAC and IOS, the video wont play, but the same URL plays on PC and Android

https://apps.basereality.tv:8443/stream.php?k=%3dEB95_7%403Fe%40_f%3fC%3e%3b%60Ad%3daf49UGH2aal%60UIFC%3dl%3a%3e286D%5e%600cb65h_6_fbf7b5_7de_fdhcghd264%60fa%5d%3eAc__.mp4

Click on the video link with Chrome, FireFox, Edge, and Opera Browsers and the video plays.

**Your Setup (please complete the following information):**
 - Unity version: 2018.3.14
 - AVPro Video version: 1.10.1
 - Operating system version: Catalina
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1.  URL to player on MAC or IOS video wont play, but same link works on PC and Android versions of the player

https://apps.basereality.tv:8443/stream.php?k=%3dEB95_7%403Fe%40_f%3fC%3e%3b%60Ad%3daf49UGH2aal%60UIFC%3dl%3a%3e286D%5e%600cb65h_6_fbf7b5_7de_fdhcghd264%60fa%5d%3eAc__.mp4

**Videos**

https://apps.basereality.tv:8443/stream.php?k=%3dEB95_7%403Fe%40_f%3fC%3e%3b%60Ad%3daf49UGH2aal%60UIFC%3dl%3a%3e286D%5e%600cb65h_6_fbf7b5_7de_fdhcghd264%60fa%5d%3eAc__.mp4

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by nsmith1024** [comment]
Any news on this? Cant release IOS version of my app until this is solved, thanks

**Comment by AndrewRH** [comment]
Hi,

So the extension is .php which is why it can't stream the file.   The other part of the URL is a parameter token.  Your script should rather perhaps redirect to the mp4 file itself, so that you return the URL to the mp4 file directly.

I know it's a pain, but that's just how Apple's stuff works.

Hope that helps to explain the issue.

Thanks,

**Comment by nsmith1024** [comment]
It cant redirect to the file itself because then the file would be directly exposed to the internet which is the point of the stream.php script to prevent that, it fetches the file fro a secure place and sends it to the app.

Why is the player checking that there is a .php and parameters in the filename, wouldnt it just check the file extension to see its an mp4 file and just start playing it? Why is it concerned about the file name itself?

The same code works when built for PC and for Android with no changes, its the same player same code and everything.

I thought AVPRoVideo allows for the same API for different platforms??? Which is what we are doing.

**Comment by MorrisRH** [comment]
The request is currently failing with the following errors:
-12939: byte range and no content length
-11850: The server is not correctly configured.

You might be able to resolve this by including the Content-Length header in the server's http response.

**Comment by nsmith1024** [comment]
But its the same server for PC and Android, and the same video file, and same AVProVideo function call, why is this a problem only when played on MAC and IOS?

**Comment by AndrewRH** [comment]
In our experience, Apple's API's are very pedantic about specs.  They have a lot more guidelines on how things should work, and they tend not to support edge cases like other platforms.  We've run into these sorts of issues many times.  For for why it plays in browsers, the browsers have their own low-level implementation that they've written themselves, so they're not as reliant on Apple API's, and they will have their own code to do the downloading of the data and then feed that into hardware decoders.  We're using Apple's API's for playback so there are some differences.
I presume the errors that Morris mentioned are what he's seeing reported from the Apple API's, and they're usually a good indicator about what the API isn't happy about.

**Comment by nsmith1024** [comment]
I added the Content-Length but its still not playing, can you check it please?

**Comment by AndrewRH** [comment]
@MorrisRH

**Comment by MorrisRH** [comment]
I'm not sure your server is handling byte range requests correctly. According to Apple:

> HTTP servers hosting media files for iOS must support byte-range requests, which iOS uses to perform random access in media playback. (Byte-range support is also known as content-range or partial-range support.) Most, but not all, HTTP 1.1 servers already support byte-range requests.

Taken from their documentation [here](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/CreatingVideoforSafarioniPhone/CreatingVideoforSafarioniPhone.html#//apple_ref/doc/uid/TP40006514-SW6
).

**Comment by nsmith1024** [comment]
What is it doing wrong? 

Do you have a link to a video on the internet that plays on MAC/IOS using your player so i can check the internet traffic?

**Comment by MorrisRH** [comment]
The following shows the headers from an mp4 request using nginx for the server.
The first request is just for the byte range 0-1.
The second request requests the whole range.
Both responses return a status code of 206 (partial content) and include the Content-Length and Content-Range headers.

Request
GET /Video/Ink_in_water_720p30.mp4 HTTP/1.1
Accept: */*
Connection: Keep-Alive
**Range: bytes=0-1**
Host: localhost:8080
Accept-Language: en-gb
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15
Referer: http://localhost:8080/Video/
Accept-Encoding: identity
X-Playback-Session-Id: 077A35FB-4807-4515-9846-5C51846FD384

Response
HTTP/1.1 206 Partial Content
Content-Type: video/mp4
Connection: keep-alive
Last-Modified: Wed, 27 May 2020 15:12:12 GMT
**Content-Range: bytes 0-1/7959270**
Date: Fri, 24 Jul 2020 07:30:38 GMT
**Content-Length: 2**
ETag: "5ece834c-7972e6"
Server: nginx/1.19.1

Request
GET /Video/Ink_in_water_720p30.mp4 HTTP/1.1
Accept: */*
Connection: Keep-Alive
**Range: bytes=0-7959269**
Host: localhost:8080
Accept-Language: en-gb
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15
Referer: http://localhost:8080/Video/
Accept-Encoding: identity
X-Playback-Session-Id: 077A35FB-4807-4515-9846-5C51846FD384

Response
HTTP/1.1 206 Partial Content
Content-Type: video/mp4
Connection: keep-alive
Last-Modified: Wed, 27 May 2020 15:12:12 GMT
**Content-Range: bytes 0-7959269/7959270**
Date: Fri, 24 Jul 2020 07:30:38 GMT
**Content-Length: 7959270**
ETag: "5ece834c-7972e6"
Server: nginx/1.19.1

**Comment by nsmith1024** [comment]
Ok, i jimmied with the server and php script, now it reports bytes and is able to seek to any spot in the video and can send back the number of bytes requested from the low tolerance high requirements Apple Gods.

The video is playing, but it has no sound and has bright red tint over the whole video. Maybe server needs more modifications?

**Comment by MorrisRH** [comment]
The red tint is due to using Y'CbCr textures which require shader support. This works with our shaders but if you're using your own then you'll need to either:
- disable Y'CbCr in the platform specific section of the media player inspector. This will switch to using standard RGBA textures at the cost of doubling memory usage (which may or may not be a problem for you).
- take a look at how we implemented in our shaders and modify your own to suit.

**Comment by nsmith1024** [comment]
That fixed the red, but there is no sound!

**Comment by nsmith1024** [comment]
Some files still dont play using your player on MAC/IOS, but it can be played using safari on MAC, Please try this link

https://apps.basereality.tv:8443/stream.php?k=Ga%3a4%3a_27hAceE8F%3bd%60%3bA5_ceCBUGH2aal%60UIFC%3dl%3a%3e286D%5e%600g46665h3b36h3f%60eh_ea4hd54342b7%603%5d%3eAc__.mp40

**Comment by MorrisRH** [comment]
That link played fine in our demo scene.

**Comment by MorrisRH** [comment]
On iOS, the link is working occasionally, when it fails the error reported is "Network error - HTTP Parse Failure"

**Comment by MorrisRH** [comment]
The audio isn't working because the audio track doesn't have a language set, it's 'und'. For reasons unknown the underlying system won't default to it. If it's English then it will work.

**Comment by nsmith1024** [comment]
But it plays in safari browser on MAC, it also plays on PC, and Android using your player. So how can i fix it?

**Comment by nsmith1024** [comment]
When it gives the error "Network error - HTTP Parse Failure", can you see what data its sending back? is it a HTML Capture Challege to verify that you are not a robot, instead of the video data?

**Comment by nsmith1024** [comment]
> 
> 
> The audio isn't working because the audio track doesn't have a language set, it's 'und'. For reasons unknown the underlying system won't default to it. If it's English then it will work.

I cant control what language the video has in it, the player should not be so sensitive to so many things. Does it only work if everything is perfect?

The video plays on MAC using safari, and it plays using your own player for PC, and Android, i dont know what else to do becuase i cant control what language the video has in it.

**Comment by MorrisRH** [comment]
That's an ssl handshake failure. I've seen it with your videos on macOS and iOS. This is low-level networking and not something we have any control over in the plugin. I'm not sure why it succeeds the second time.

Using ffplay it fails every time which might be useful to you to aid in debugging.

Your server is also behaving oddly. The request for the full content fails at the end which leads to continuous requests for the final byte, as shown here:

![Screenshot 2020-07-25 at 16 35 57](https://user-images.githubusercontent.com/46530460/88460577-1e2dfa00-ce95-11ea-98df-58e9ff26f4f0.png)

**Comment by nsmith1024** [comment]
The whole app is using SSL for communication with the same server, getting the video is only one operation of many different operations, fetching and saving images and video, fetching and saving user data, etc, all works, on all platforms. Very strange that only on IOS fetching video is failing, but it uses the same stream.php to fetch images and all that works, only the video dont. I was wondering if you could post an SSL link to a video that is on the internet, this way i can try that link to see how the traffic is different from what mine is doing.

**Comment by nsmith1024** [comment]
Good news it works on the iPhone device, but not in the emulator. Only problem is auto reply dont seem to work on iPhone.

**Comment by MorrisRH** [comment]
The video isn't looping due to the server requests never finishing.
You can see this in Safari's web developer console (network tab). The "stream.php — Byte Range 0-5331380" fails at the end with a network error, after which the player continuously requests the final byte, "stream.php — Byte Range 5331380-5331380".

A good example of mp4 progressive download is the following: https://assets.mixkit.co/videos/preview/mixkit-matterhorn-mountain-landscape-4281-large.mp4

**Comment by nsmith1024** [comment]
But why is it asking for byte range  5331380-5331380, there are no bytes in that range so whats it supposed to return?

Can you help me understand this because i dont understand what the server supposed to do in this case?

Seems after we pass this it should work, so can you help?

Thanks

**Comment by MorrisRH** [comment]
The link failed to play in Safari on macOS with the following headers:

>Summary
URL: https://apps.basereality.tv:8443/stream.php?k=g%3c8E%3aA7DcA%3d3GDeCc%3dEaF8F7adUGH2aal%60UIFC%3dl%3a%3e286D%5e%600543b_5%60aage5dgedgha7aa2aa%60f%60d3bg%5d%3eAc__.mp4
Status: 200
Source: Network
>
>Request
Accept: */*
Range: bytes=0-39820690
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.2 Safari/605.1.15
Referer: https://apps.basereality.tv:8443/stream.php?k=g%3c8E%3aA7DcA%3d3GDeCc%3dEaF8F7adUGH2aal%60UIFC%3dl%3a%3e286D%5e%600543b_5%60aage5dgedgha7aa2aa%60f%60d3bg%5d%3eAc__.mp4
Accept-Encoding: identity
Connection: Keep-Alive
X-Playback-Session-Id: B3890462-D84A-406A-87A9-EC429C7D8CAE
>
>Response
Content-Type: video/mp4
Pragma: no-cache
Cache-Control: no-store, no-cache, must-revalidate, max-age=0, post-check=0, pre-check=0
Date: Tue, 28 Jul 2020 08:19:58 GMT
Content-Length: 39820691
Accept-Ranges: bytes
Content-Range: bytes 0-39820690/39820691
X-Frame-Options: SAMEORIGIN
x-powered-by: PHP/7.1.29
cf-request-id: 04361ad9220000f3ffba1ab200000001
Server: cloudflare
cf-cache-status: DYNAMIC
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
cf-ray: 5b9d2da1dd95f3ff-LHR
>
>Query String Parameters
k: g<8E:A7DcA=3GDeCc=EaF8F7adUGH2aal`UIFC=l:>286D^`0543b_5`aage5dgedgha7aa2aa`f`d3bg]>Ac__.mp4

Loading the page a second time it worked fine.

Using the plugin on iOS I'm seeing similar with the video failing to play, and then successfully playing on the next attempt.
The error output when the video fails to play is:
>Player 701: failed to load asset https://apps.basereality.tv:8443/stream.php?k=g%3c8E%3aA7DcA%3d3GDeCc%3dEaF8F7adUGH2aal%60UIFC%3dl%3a%3e286D%5e%600543b_5%60aage5dgedgha7aa2aa%60f%60d3bg%5d%3eAc__.mp4
Player 701: Error: Domain=AVFoundationErrorDomain Code=-11829 "Cannot Open" - This media may be damaged.
Player 701: Underlying Error: Domain=NSOSStatusErrorDomain Code=-12848 "The operation couldn’t be completed. (OSStatus error -12848.)" - (null)

This is very suggestive of the issue being server side. It is very unlikely I'll be able to get anymore error information out of the system than this. If you can check the server logs the next time playback fails, hopefully you'll be able to see what is causing the underlying issue.
