### ISSUE TITLE
Android video decoding slightly blurs adjacent pixels even with POINT filter

### ISSUE THREAD

**Issue by acgourley** [RenderHeads/UnityPlugin-AVProVideo#791]
We have an application where precise decoding of the pixel data is important to us. For this reason we put the MediaPlayer texture filter into POINT mode. In the editor this works great, and our test video which looks like:

https://www.dropbox.com/s/t2qts9r5lc1x577/rgb64_yuv420_x265.mp4?dl=0
![rgb64](https://user-images.githubusercontent.com/7680/118729380-aac1f400-b7ea-11eb-9c7e-42ecce3161d3.png)

In editor with POINT filter, it renders like:
<img width="872" alt="Screen Shot 2021-05-18 at 2 51 28 PM" src="https://user-images.githubusercontent.com/7680/118728564-3d619380-b7e9-11eb-9b1a-78c28dc7dd9d.png">

But when built to android, it renders like this (see banding between colors) 
![Screenshot_20210518-144052](https://user-images.githubusercontent.com/7680/118728601-50746380-b7e9-11eb-8ccf-e1c541de453c.png)

Note that turning on bilinear makes it appear even more blurry this, so it cannot just be that POINT isn't being set right:
![Screenshot_20210518-144020](https://user-images.githubusercontent.com/7680/118728918-cf699c00-b7e9-11eb-94c1-11e1949911a1.png)

And turning on OES mode seems to fix it, looking like below, although this isn't a good solution for us because we're using HLSL shaders: 
![Screenshot_20210518-144338](https://user-images.githubusercontent.com/7680/118729066-15266480-b7ea-11eb-9461-2079d93847d8.png)

Is there a way to get the correct pixels all the way from exoplayer to Unity via AVPro without any pixels blurring? 

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.2f1
 - AVPro Video version: 2.1.3 Core
 - Operating system version: OSX / Android 11
 - Device model: Pixel 3 XL (We also observe this problem on Oculus Quest)

**Comment by AndrewRH** [comment]
If OES is correct, then we may want to change our internal blit to use point sample, though it shouldn't make a difference whether point/linear sampling is used if the texture as the same size...but I guess with OES it could be any representation, and if it's YUV420 then the 'textures' may not be the same size.    It'd be interesting to see if this fixes it - then we may consider whether to make this the default behaviour or exposing a new option for this.

Alternatively you could encode your video without chroma sub-sampling (ie as 4:4:4 instead of the default 4:2:0), this should fix it too, but I'm not sure how common 4:4:4 decoding is on Android.

For interest - On Windows it has the same rendering as on Android.  I guess it's related to how the chroma channels are resolved - how the sampling and/or interpolation is done.

just my 2c

**Comment by jmccready** [comment]
I noticed this same issue on mac when using AVPro 1 ( not being able to get sharp edges out of videos regardless of encoding)  and it thankfully got fixed when i upgraded to AVPro2.  For mac at least. Seems like the slight pixel blending still happens for android and windows though.

**Comment by acgourley** [comment]
> Alternatively you could encode your video without chroma sub-sampling (ie as 4:4:4 instead of the default 4:2:0), this should fix it too, but I'm not sure how common 4:4:4 decoding is on Android.

My Pixel 3 XL, at least, does not manage to load the YUV444 image to test this. However, I tried encoding a [greyscale version of this video](https://www.dropbox.com/s/lf0mjvjc8mb17hc/bw64_yuv420_x265.mp4?dl=0) and that loads sharp without any banding where the black and white pixels meet. Does this confirm your theory about the internal blit?

**Comment by AndrewRH** [comment]
@RenderHeadsSte  perhaps you could look into this at some point - see whether changing the internal blit to point sampling (if it isn't already) fixes this issue..  I wonder if it could also fix another issue I remember where someone said the video was slightly blurrier in our player on Android compared to another one.

**Comment by RenderHeadsSte** [comment]
I think we have a fix for this.  Just deciding how best to present it.  Should make it into the next build.

**Comment by jmccready** [comment]
I've been thinking about this issue the last few days and correct me if i'm wrong here:  When video is encoded at yuv420 the chroma information is at half resolution.  Probably for most applications the right thing to do when creating the full res rgb image from a decoded frame is to deblock (smooth out) out those chroma channels once they are decoded to full resolution so that there aren't blocky color boundaries.  And that is what is happening most of the time (but not on mac in avpro 2).  For some applications however it might be desirable to keep the decoded frame as un-messed-with as possible so it would be nice to have an option to toggle off this chroma deblocking.

**Comment by RenderHeadsSte** [comment]
A fix has been implemented.  It will be included in the next build.

**Comment by acgourley** [comment]
Thank you for being so quick about it, excited to try 2.1.4

**Comment by RenderHeadsSte** [comment]
With 2.1.4 released now, please do let us know how you get on with the fix @acgourley

**Comment by acgourley** [comment]
Confirmed that with 2.1.4 on my Pixel 3 XL the test video is now sharp like it is in the editor. Thanks for fixing this!
