### ISSUE TITLE
AVPro video error on Android, ARM64 IL2CPP not supported rendering video

### ISSUE THREAD

**Issue by binnyXR** [RenderHeads/UnityPlugin-AVProVideo#81]
**Describe the bug**

I have been using your asset AVPro for quite some time now both in IOS and Android, but recently PlayStore requires to build the app with the x64 architecture and it seems your asset is not working with this new changes since it doesn't show the Video when debugged in Android, as it works fine with Unity Editor. Please can you provide me with some instructions on how to deal with this issue.

**Your Setup (please complete the following information):**
 - Unity version: 2019.1.4f1 
 - AVPro Video version: 1.9.16
 - Operating system version: MACOS
 - Device model: Samsung S8
 - Video specs (resolution, frame-rate, codec, file size): H264

**Comment by AndrewRH** [comment]
Thanks for submitting your reports.

A few questions:

1) Which platform are you finding it not supported on?
2) If it's Android, did you go to the Plugins/Android/libs/arm64-v8a folder and check that each file in there is set to ARM64 in the Inspector window?

**Comment by binnyXR** [comment]
First Thanks for Replaying 🥇 
Platform Ive used : Android,
i checked on Plugins/Android/libs/arm64-v8a the files is there but when i build and publish an Play store and test it in mobile device, the videos dosen't renderer it's not showing.

**Comment by AndrewRH** [comment]
Okay, so the files are there - but did you check in the Inspector Window that they're assigned the correct platform and architecture?

**Comment by cdytoby** [comment]
I can confirm it. The files are not "assigned" to android platform. Have to do it manually with each update. Please fix.

**Comment by AndrewRH** [comment]
Great!
We will try to fix it... the problem is that we support a wide range of Unity versions, and some versions don't support ARM64, so we're not able to set it....It's something we're looking into.

So does this fix the build issue you were having?

**Comment by AndrewRH** [comment]
Closing this issue now as the fix should resolve it.

**Comment by RemyRM** [comment]
@AndrewRH I can confirm that the `arm64-v8a/libAVProLocal.so` lib is not set to `Android` by default, resulting in the following linking error when building for Android:

`AndroidPlayer(ADB@127.0.0.1:34999) AndroidJavaException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.company.project-1/base.apk"],nativeLibraryDirectories=[/data/app/com.company.project-1/lib/arm64, /data/app/com.company.project-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libAVProLocal.so"
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.company.project-1/base.apk"],nativeLibraryDirectories=[/data/app/com.company.project-1/lib/arm64, /data/app/com.company.project-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libAVProLocal.so"
`

Setting the target platform to Android fixes it 👍

**Comment by ismaelash** [comment]
Thank you @RemyRM

**Comment by michelepanegrossi** [comment]
> @AndrewRH I can confirm that the `arm64-v8a/libAVProLocal.so` lib is not set to `Android` by default, resulting in the following linking error when building for Android:
> 
> `AndroidPlayer(ADB@127.0.0.1:34999) AndroidJavaException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.company.project-1/base.apk"],nativeLibraryDirectories=[/data/app/com.company.project-1/lib/arm64, /data/app/com.company.project-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libAVProLocal.so" java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.company.project-1/base.apk"],nativeLibraryDirectories=[/data/app/com.company.project-1/lib/arm64, /data/app/com.company.project-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libAVProLocal.so" `
> 
> Setting the target platform to Android fixes it 👍

Thanks @RemyRM I can confirm the issue is still there with Unity 2020.1.6f1 and AVPro. version 1.11.5
